import type { TenantConfig } from './schema';
import { FieldType } from './schema';

const tenants: Record<string, TenantConfig> = {
  'dental-demo': {
    tenantId: 'dental-demo',
    templateKey: 'generic-dental',
    theme: {
      primary: '#0ea5e9',
      secondary: '#0369a1',
      accent: '#f0abfc',
      font: 'Georgia, serif',
    },
    seo: {
      title: 'Clínica Dental Demo — Sonríe con Confianza',
      description:
        'Atención dental de primer nivel. Tratamientos personalizados para toda la familia.',
      robots: 'index, follow',
    },
    content: {
      templateKey: 'generic-dental',
      version: '1.0.0',
      sections: [
        {
          id: 'hero',
          type: 'hero',
          active: true,
          order: 1,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: 'Sonríe con Confianza',
              active: true,
              label: 'Main Heading',
            },
            {
              id: 'subheading',
              type: FieldType.text,
              value: 'Atención dental de primer nivel para toda la familia.',
              active: true,
              label: 'Subheading',
            },
            {
              id: 'cta_label',
              type: FieldType.text,
              value: 'Reservar Cita',
              active: true,
              label: 'CTA Button Text',
            },
            {
              id: 'cta_url',
              type: FieldType.url,
              value: '#contacto',
              active: true,
              label: 'CTA Button URL',
            },
            {
              id: 'image_url',
              type: FieldType.image,
              value: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=1200&q=80',
              active: true,
              label: 'Hero Image',
            },
          ],
        },
        {
          id: 'testimonials',
          type: 'testimonials',
          active: true,
          order: 2,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: 'Lo que dicen nuestros pacientes',
              active: true,
              label: 'Section Heading',
            },
            {
              id: 'testimonial_1_name',
              type: FieldType.text,
              value: 'María García',
              active: true,
              label: 'Testimonial 1 Name',
            },
            {
              id: 'testimonial_1_text',
              type: FieldType.richtext,
              value:
                'Excelente atención. El equipo es muy profesional y amable. ¡Mi sonrisa nunca se vio mejor!',
              active: true,
              label: 'Testimonial 1 Text',
            },
            {
              id: 'testimonial_1_rating',
              type: FieldType.number,
              value: 5,
              active: true,
              label: 'Testimonial 1 Rating',
            },
            {
              id: 'testimonial_2_name',
              type: FieldType.text,
              value: 'Carlos López',
              active: true,
              label: 'Testimonial 2 Name',
            },
            {
              id: 'testimonial_2_text',
              type: FieldType.richtext,
              value:
                'Me hicieron sentir cómodo desde el primer momento. El tratamiento fue rápido y sin dolor.',
              active: true,
              label: 'Testimonial 2 Text',
            },
            {
              id: 'testimonial_2_rating',
              type: FieldType.number,
              value: 5,
              active: true,
              label: 'Testimonial 2 Rating',
            },
            {
              id: 'testimonial_3_name',
              type: FieldType.text,
              value: 'Ana Martínez',
              active: true,
              label: 'Testimonial 3 Name',
            },
            {
              id: 'testimonial_3_text',
              type: FieldType.richtext,
              value:
                'Llevé a mis hijos y quedaron encantados. El dentista tiene mucha paciencia con los niños.',
              active: true,
              label: 'Testimonial 3 Text',
            },
            {
              id: 'testimonial_3_rating',
              type: FieldType.number,
              value: 4,
              active: true,
              label: 'Testimonial 3 Rating',
            },
          ],
        },
        {
          id: 'location',
          type: 'location',
          active: true,
          order: 3,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: 'Encuéntranos',
              active: true,
              label: 'Section Heading',
            },
            {
              id: 'address',
              type: FieldType.text,
              value: 'Calle Principal 123, Ciudad, País',
              active: true,
              label: 'Address',
            },
            {
              id: 'phone',
              type: FieldType.text,
              value: '+1 (555) 000-1234',
              active: true,
              label: 'Phone',
            },
            {
              id: 'email',
              type: FieldType.text,
              value: 'contacto@clinicadental.demo',
              active: true,
              label: 'Email',
            },
            {
              id: 'hours',
              type: FieldType.text,
              value: 'Lunes–Viernes: 9:00–18:00 | Sábado: 9:00–14:00',
              active: true,
              label: 'Business Hours',
            },
            {
              id: 'map_url',
              type: FieldType.url,
              value: 'https://maps.google.com',
              active: true,
              label: 'Google Maps URL',
            },
          ],
        },
        {
          id: 'cta',
          type: 'cta',
          active: true,
          order: 4,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: '¿Listo para tu próxima cita?',
              active: true,
              label: 'CTA Heading',
            },
            {
              id: 'subheading',
              type: FieldType.text,
              value: 'Agenda tu consulta hoy y recibe tu primera revisión sin costo.',
              active: true,
              label: 'CTA Subheading',
            },
            {
              id: 'button_label',
              type: FieldType.text,
              value: 'Agendar Ahora',
              active: true,
              label: 'Button Label',
            },
            {
              id: 'button_url',
              type: FieldType.url,
              value: 'mailto:contacto@clinicadental.demo',
              active: true,
              label: 'Button URL',
            },
          ],
        },
      ],
    },
  },

  'legal-demo': {
    tenantId: 'legal-demo',
    templateKey: 'generic-legal',
    theme: {
      primary: '#1e3a5f',
      secondary: '#2d5986',
      accent: '#c9a84c',
      font: 'Garamond, Georgia, serif',
    },
    seo: {
      title: 'Legal Firm Demo — Defending Your Rights',
      description:
        'Expert legal representation for individuals and businesses. Justice is our mission.',
      robots: 'index, follow',
    },
    content: {
      templateKey: 'generic-legal',
      version: '1.0.0',
      sections: [
        {
          id: 'hero',
          type: 'hero',
          active: true,
          order: 1,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: 'Defending Your Rights',
              active: true,
              label: 'Main Heading',
            },
            {
              id: 'subheading',
              type: FieldType.text,
              value:
                'Experienced attorneys committed to justice for individuals and businesses alike.',
              active: true,
              label: 'Subheading',
            },
            {
              id: 'cta_label',
              type: FieldType.text,
              value: 'Free Consultation',
              active: true,
              label: 'CTA Button Text',
            },
            {
              id: 'cta_url',
              type: FieldType.url,
              value: '#contact',
              active: true,
              label: 'CTA Button URL',
            },
            {
              id: 'image_url',
              type: FieldType.image,
              value: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&q=80',
              active: true,
              label: 'Hero Image',
            },
          ],
        },
        {
          id: 'testimonials',
          type: 'testimonials',
          active: true,
          order: 2,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: 'Client Testimonials',
              active: true,
              label: 'Section Heading',
            },
            {
              id: 'testimonial_1_name',
              type: FieldType.text,
              value: 'James Harrison',
              active: true,
              label: 'Testimonial 1 Name',
            },
            {
              id: 'testimonial_1_text',
              type: FieldType.richtext,
              value:
                'The team handled my case with professionalism and expertise. Outstanding results.',
              active: true,
              label: 'Testimonial 1 Text',
            },
            {
              id: 'testimonial_1_rating',
              type: FieldType.number,
              value: 5,
              active: true,
              label: 'Testimonial 1 Rating',
            },
            {
              id: 'testimonial_2_name',
              type: FieldType.text,
              value: 'Sandra Williams',
              active: true,
              label: 'Testimonial 2 Name',
            },
            {
              id: 'testimonial_2_text',
              type: FieldType.richtext,
              value:
                'They fought tirelessly for my rights. I could not have asked for better representation.',
              active: true,
              label: 'Testimonial 2 Text',
            },
            {
              id: 'testimonial_2_rating',
              type: FieldType.number,
              value: 5,
              active: true,
              label: 'Testimonial 2 Rating',
            },
            {
              id: 'testimonial_3_name',
              type: FieldType.text,
              value: 'Robert Chen',
              active: true,
              label: 'Testimonial 3 Name',
            },
            {
              id: 'testimonial_3_text',
              type: FieldType.richtext,
              value:
                'Transparent communication and exceptional legal strategy. Highly recommended firm.',
              active: true,
              label: 'Testimonial 3 Text',
            },
            {
              id: 'testimonial_3_rating',
              type: FieldType.number,
              value: 5,
              active: true,
              label: 'Testimonial 3 Rating',
            },
          ],
        },
        {
          id: 'location',
          type: 'location',
          active: true,
          order: 3,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: 'Our Office',
              active: true,
              label: 'Section Heading',
            },
            {
              id: 'address',
              type: FieldType.text,
              value: '500 Justice Ave, Suite 300, New York, NY 10001',
              active: true,
              label: 'Address',
            },
            {
              id: 'phone',
              type: FieldType.text,
              value: '+1 (212) 555-9876',
              active: true,
              label: 'Phone',
            },
            {
              id: 'email',
              type: FieldType.text,
              value: 'info@legalfirm.demo',
              active: true,
              label: 'Email',
            },
            {
              id: 'hours',
              type: FieldType.text,
              value: 'Monday–Friday: 8:00 AM – 6:00 PM | Emergency: 24/7',
              active: true,
              label: 'Business Hours',
            },
            {
              id: 'map_url',
              type: FieldType.url,
              value: 'https://maps.google.com',
              active: true,
              label: 'Google Maps URL',
            },
          ],
        },
        {
          id: 'cta',
          type: 'cta',
          active: true,
          order: 4,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: 'Get the Representation You Deserve',
              active: true,
              label: 'CTA Heading',
            },
            {
              id: 'subheading',
              type: FieldType.text,
              value: 'Schedule your free consultation today. No obligation, confidential.',
              active: true,
              label: 'CTA Subheading',
            },
            {
              id: 'button_label',
              type: FieldType.text,
              value: 'Book a Free Consultation',
              active: true,
              label: 'Button Label',
            },
            {
              id: 'button_url',
              type: FieldType.url,
              value: 'mailto:info@legalfirm.demo',
              active: true,
              label: 'Button URL',
            },
          ],
        },
      ],
    },
  },

  'client-a': {
    tenantId: 'client-a',
    templateKey: 'custom-client-a',
    theme: {
      primary: '#16a34a',
      secondary: '#15803d',
      accent: '#fbbf24',
      font: 'Helvetica Neue, Arial, sans-serif',
    },
    seo: {
      title: 'Dental Pro — Los mejores dentistas de tu ciudad',
      description:
        'Dental Pro: tratamientos avanzados, precios accesibles y atención personalizada.',
      robots: 'index, follow',
    },
    content: {
      templateKey: 'custom-client-a',
      version: '1.0.0',
      sections: [
        {
          id: 'hero',
          type: 'hero',
          active: true,
          order: 1,
          fields: [
            {
              id: 'heading_template',
              type: FieldType.text,
              value: 'Los {0} dentistas más confiables',
              active: true,
              label: 'Heading Template ({0} = city)',
            },
            {
              id: 'city',
              type: FieldType.text,
              value: 'Miami',
              active: true,
              label: 'City Name',
            },
            {
              id: 'subheading',
              type: FieldType.text,
              value: 'Tecnología de punta y un equipo que se preocupa por tu salud bucal.',
              active: true,
              label: 'Subheading',
            },
            {
              id: 'cta_label',
              type: FieldType.text,
              value: 'Agenda tu Cita Gratis',
              active: true,
              label: 'CTA Button Text',
            },
            {
              id: 'cta_url',
              type: FieldType.url,
              value: '#contacto',
              active: true,
              label: 'CTA Button URL',
            },
            {
              id: 'badge',
              type: FieldType.text,
              value: '⭐ #1 en satisfacción del paciente',
              active: true,
              label: 'Hero Badge',
            },
            {
              id: 'image_url',
              type: FieldType.image,
              value: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=1200&q=80',
              active: true,
              label: 'Hero Image',
            },
          ],
        },
        {
          id: 'testimonials',
          type: 'testimonials',
          active: true,
          order: 2,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: 'Pacientes felices en toda la ciudad',
              active: true,
              label: 'Section Heading',
            },
            {
              id: 'testimonial_1_name',
              type: FieldType.text,
              value: 'Luisa Fernández',
              active: true,
              label: 'Testimonial 1 Name',
            },
            {
              id: 'testimonial_1_text',
              type: FieldType.richtext,
              value: '¡El mejor servicio dental que he tenido! El personal es increíble.',
              active: true,
              label: 'Testimonial 1 Text',
            },
            {
              id: 'testimonial_1_rating',
              type: FieldType.number,
              value: 5,
              active: true,
              label: 'Testimonial 1 Rating',
            },
            {
              id: 'testimonial_2_name',
              type: FieldType.text,
              value: 'Diego Ruiz',
              active: true,
              label: 'Testimonial 2 Name',
            },
            {
              id: 'testimonial_2_text',
              type: FieldType.richtext,
              value: 'Vine con miedo al dentista y salí con una enorme sonrisa. ¡100% recomendado!',
              active: true,
              label: 'Testimonial 2 Text',
            },
            {
              id: 'testimonial_2_rating',
              type: FieldType.number,
              value: 5,
              active: true,
              label: 'Testimonial 2 Rating',
            },
            {
              id: 'testimonial_3_name',
              type: FieldType.text,
              value: 'Patricia Vega',
              active: true,
              label: 'Testimonial 3 Name',
            },
            {
              id: 'testimonial_3_text',
              type: FieldType.richtext,
              value: 'Precios justos y resultados extraordinarios. Sin duda el mejor de Miami.',
              active: true,
              label: 'Testimonial 3 Text',
            },
            {
              id: 'testimonial_3_rating',
              type: FieldType.number,
              value: 5,
              active: true,
              label: 'Testimonial 3 Rating',
            },
          ],
        },
        {
          id: 'location',
          type: 'location',
          active: true,
          order: 3,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: 'Visítanos en Miami',
              active: true,
              label: 'Section Heading',
            },
            {
              id: 'address',
              type: FieldType.text,
              value: '1200 Brickell Ave, Suite 450, Miami, FL 33131',
              active: true,
              label: 'Address',
            },
            {
              id: 'phone',
              type: FieldType.text,
              value: '+1 (305) 555-7890',
              active: true,
              label: 'Phone',
            },
            {
              id: 'email',
              type: FieldType.text,
              value: 'hola@dentalpro.demo',
              active: true,
              label: 'Email',
            },
            {
              id: 'hours',
              type: FieldType.text,
              value: 'Lunes–Sábado: 8:00–20:00 | Domingo: Urgencias',
              active: true,
              label: 'Business Hours',
            },
            {
              id: 'map_url',
              type: FieldType.url,
              value: 'https://maps.google.com',
              active: true,
              label: 'Google Maps URL',
            },
          ],
        },
        {
          id: 'cta',
          type: 'cta',
          active: true,
          order: 4,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: 'Tu mejor sonrisa empieza hoy',
              active: true,
              label: 'CTA Heading',
            },
            {
              id: 'subheading',
              type: FieldType.text,
              value: 'Primera consulta gratis. Sin compromisos. Solo resultados.',
              active: true,
              label: 'CTA Subheading',
            },
            {
              id: 'button_label',
              type: FieldType.text,
              value: 'Llamar Ahora',
              active: true,
              label: 'Button Label',
            },
            {
              id: 'button_url',
              type: FieldType.url,
              value: 'tel:+13055557890',
              active: true,
              label: 'Button URL',
            },
          ],
        },
      ],
    },
  },

  'client-b': {
    tenantId: 'client-b',
    templateKey: 'custom-client-b',
    theme: {
      primary: '#7c3aed',
      secondary: '#5b21b6',
      accent: '#10b981',
      font: 'Inter, system-ui, sans-serif',
    },
    seo: {
      title: 'Nexus Consulting — Strategic Legal & Business Advisory',
      description:
        'Nexus Consulting delivers elite legal and business strategy for modern enterprises.',
      robots: 'index, follow',
    },
    content: {
      templateKey: 'custom-client-b',
      version: '1.0.0',
      sections: [
        {
          id: 'hero',
          type: 'hero',
          active: true,
          order: 1,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: 'Strategic Advisory for the Modern Enterprise',
              active: true,
              label: 'Main Heading',
            },
            {
              id: 'subheading',
              type: FieldType.text,
              value:
                'Nexus Consulting brings together elite legal minds and business strategists to accelerate your growth.',
              active: true,
              label: 'Subheading',
            },
            {
              id: 'cta_label',
              type: FieldType.text,
              value: 'Start Your Strategy Session',
              active: true,
              label: 'CTA Button Text',
            },
            {
              id: 'cta_url',
              type: FieldType.url,
              value: '#engage',
              active: true,
              label: 'CTA Button URL',
            },
            {
              id: 'stat_1_value',
              type: FieldType.text,
              value: '500+',
              active: true,
              label: 'Stat 1 Value',
            },
            {
              id: 'stat_1_label',
              type: FieldType.text,
              value: 'Clients Served',
              active: true,
              label: 'Stat 1 Label',
            },
            {
              id: 'stat_2_value',
              type: FieldType.text,
              value: '$2B+',
              active: true,
              label: 'Stat 2 Value',
            },
            {
              id: 'stat_2_label',
              type: FieldType.text,
              value: 'Deals Closed',
              active: true,
              label: 'Stat 2 Label',
            },
            {
              id: 'stat_3_value',
              type: FieldType.text,
              value: '20+',
              active: true,
              label: 'Stat 3 Value',
            },
            {
              id: 'stat_3_label',
              type: FieldType.text,
              value: 'Years of Excellence',
              active: true,
              label: 'Stat 3 Label',
            },
            {
              id: 'image_url',
              type: FieldType.image,
              value: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
              active: true,
              label: 'Hero Image',
            },
          ],
        },
        {
          id: 'cta',
          type: 'cta',
          active: true,
          order: 2,
          fields: [
            {
              id: 'heading',
              type: FieldType.text,
              value: 'Ready to Scale Your Business?',
              active: true,
              label: 'CTA Heading',
            },
            {
              id: 'subheading',
              type: FieldType.text,
              value:
                'Join hundreds of enterprises that trust Nexus for their most critical decisions.',
              active: true,
              label: 'CTA Subheading',
            },
            {
              id: 'button_label',
              type: FieldType.text,
              value: 'Engage Nexus Today',
              active: true,
              label: 'Button Label',
            },
            {
              id: 'button_url',
              type: FieldType.url,
              value: 'mailto:engage@nexusconsulting.demo',
              active: true,
              label: 'Button URL',
            },
          ],
        },
      ],
    },
  },
};

export function getTenantConfig(tenantId: string): TenantConfig | null {
  return tenants[tenantId] ?? null;
}
